### ISSUE TITLE
Registrate buildnumber on bug registration

### ISSUE THREAD

**Issue by wkohlschein** [wargamer/BS.Output.VSO#1]
The following feature will be very convenient to registrate the buildnumber when the bug is registered. 

Suggested feature is to extend the configuration with selection of the build configuration. 

![buildconfig](https://cloud.githubusercontent.com/assets/15668031/20671397/7df3125c-b57d-11e6-8ccb-197aa9f97cd5.jpg)

On bug registration the latest builnumber is defaulted when a build configuration is specified. An other version can be selected from the list.

![selectbuildnumber](https://cloud.githubusercontent.com/assets/15668031/20671417/89b21656-b57d-11e6-92ac-020c2a7e8301.jpg)

**Comment by wargamer** [comment]
Implemented with this commit: https://github.com/wargamer/BS.Output.VSO/commit/2777c4d1be6d4a135d78f30f277e184076842a55

**Comment by wkohlschein** [comment]
Thanks for the implementation! I would recommend to remove the build definition part from the versionnumber: "<build definition>/1.0.1.0 -> 1.0.1.0". This way it becomes inline with the version registration of the Microsoft Test manager process.
