### ISSUE TITLE
Any plan to publish a NuGet package?

### ISSUE THREAD

**Issue by AlexejHirsch** [wargamer/BS.Output.VSO#2]
Do you plan to publish you plugin as NuGet package on nuget.org? See also "Deploy a NuGet Package" on  http://docs.bugshooting.com/plugin_v3

**Comment by wargamer** [comment]
Yes. I just tried to publish the latest release as a package with the ID "BugShooting.Output.VSTS". That ID is  reserved, so the package was rejected. Would you be willing to grant me access to the reserved prefix?

**Comment by AlexejHirsch** [comment]
The nuget prefix "BugShooting" is reserved for plugins published by BugShooting. Please use any other id for your package.

**Comment by wargamer** [comment]
Done, published as BS.Output.VSTS
